### ISSUE TITLE
Issue on Long Execution Time

### ISSUE THREAD

**Issue by Gloria-cpu** [OpenXiangShan/difftest#446]
I am currently working with the difftest platform and encountered some issues. I am compiling with the following command:

make emu REF=$SPIKE_HOME/difftest/build/riscv64-spike-so XFUZZ=1 LLVM_COVER=1 FIRRTL_COVER=mux,control,line,toggle,ready_valid EMU_TRACE=1 EMU_THREAD=2 -j20

After that, I run the test cases linux.bin and microbenchi.bin from the ready-to-run repository (https://github.com/OpenXiangShan/ready-to-run/) using the command:

./build/fuzzer --coverage firrtl.toggle -- seed/***.bin

However, these tests have been running for three days without completing. I would like to confirm if this behavior is normal. Additionally, could you provide information on the approximate instruction count for these two test cases?

**Comment by poemonsense** [comment]
First, this is most likely not a difftest issue. You are running workloads from another repository with another CPU as the DUT. They are beyond the scope of difftest.

Second, generally, these workloads will have stdout outputs during simulation. However, since you don't provide any further information or the full commands, we don't know why your simulation does not exit.

We cannot provide information on instr count because we do not even know which DUT you are running and which workload you are using. Also, this is not really a difftest issue.
