### ISSUE TITLE
How to cfg vip in verilator sim flow 

### ISSUE THREAD

**Issue by wyz-icer** [OpenXiangShan/difftest#471]
I want to config VIP in verilator sim Flow， 
what can I do ？ 

done ： 
 verilator  isnot  support uvm in https://verilator.org/guide/latest/install.html

**Comment by poemonsense** [comment]
First, please use the issue templates when you open the issue. Otherwise, we may immediately close it without responding. 

Second, your question is not related to difftest. Sorry but we are unable to provide any help on integrating VIP to Verilator simulation flow. Please refer to the verilator project for help.

Thanks for understanding.
